(function(){
  'use strict';
  const form=document.getElementById('reportForm');
  const statusEl=document.getElementById('geoStatus');
  const resultsEl=document.getElementById('geoResults');
  const addressEl=document.getElementById('selectedAddress');
  const geoInput=document.getElementById('geoInput');
  const photosInput=document.getElementById('photosInput');
  const photosEl=document.getElementById('photos');
  const photoCount=document.getElementById('photoCount');
  const anonymous=document.getElementById('anonymous');
  const contactFields=document.getElementById('contactFields');
  const modal=document.getElementById('successModal');
  const ALLOWED=/\b(Salvador|Lauro de Freitas)\b/i;
  const BOUNDS=[[-38.72,-13.15],[-38.20,-12.72]];
  const CENTER=[-38.43,-12.94];
  const categoryLabels={domestico:'Lixo doméstico',entulho:'Entulho / obra',moveis:'Móveis / eletrodomésticos',poda:'Poda / vegetação',eletronicos:'Eletrônicos',perigoso:'Material potencialmente perigoso',outro:'Outro'};
  const riskLabels={passagem:'Obstrui calçada ou passagem',agua:'Próximo de bueiro, córrego ou água',cortante:'Material cortante ou potencialmente perigoso',animais:'Insetos, animais ou odor muito forte'};
  const state={step:1,coords:null,address:'',photos:[],map:null,marker:null,checking:false};

  function setStatus(text,type=''){statusEl.textContent=text;statusEl.className='geo-status'+(type?' '+type:'')}
  function showStep(n){state.step=n;document.querySelectorAll('.step-panel').forEach(p=>p.classList.toggle('active',Number(p.dataset.step)===n));document.querySelectorAll('.wstep').forEach(s=>{const i=Number(s.dataset.stepInd);s.classList.toggle('active',i===n);s.classList.toggle('done',i<n);const c=s.querySelector('.circle');c.textContent=i<n?'✓':String(i)});document.querySelector('.wizard-card').scrollIntoView({behavior:'smooth',block:'start'});if(n===4)renderReview();if(n===1&&state.map)setTimeout(()=>state.map.resize(),60)}
  function withinBounds(lng,lat){return lng>=BOUNDS[0][0]&&lng<=BOUNDS[1][0]&&lat>=BOUNDS[0][1]&&lat<=BOUNDS[1][1]}
  function localResult(text){return ALLOWED.test(text||'')}
  function displayAddress(text){return String(text||'').replace(/, Bahia, Região Nordeste, Brasil.*$/i,', BA').replace(/, Região Nordeste, Brasil.*$/i,', BA')}
  function updateSelected(){if(!state.coords){addressEl.className='selected-address empty';addressEl.innerHTML='<strong>Local ainda não definido</strong>Use sua localização, faça uma busca ou toque no mapa.';return}addressEl.className='selected-address';addressEl.innerHTML='<strong>Local selecionado</strong>'+escapeHtml(state.address||'Ponto marcado em Salvador / Lauro de Freitas')}
  function markerElement(){const el=document.createElement('div');el.className='map-pin';return el}
  function placeMarker(lng,lat,fly=true){state.coords={lng,lat};if(!state.marker){state.marker=new maplibregl.Marker({element:markerElement(),draggable:true}).setLngLat([lng,lat]).addTo(state.map);state.marker.on('dragend',async()=>{const p=state.marker.getLngLat();await validateAndSetPoint(p.lng,p.lat,false,true)})}else state.marker.setLngLat([lng,lat]);if(fly)state.map.flyTo({center:[lng,lat],zoom:16,essential:true});updateSelected()}
  function clearPoint(){state.coords=null;state.address='';if(state.marker){state.marker.remove();state.marker=null}geoInput.value='';resultsEl.classList.remove('show');resultsEl.innerHTML='';setStatus('');updateSelected();state.map.easeTo({center:CENTER,zoom:11.2})}

  async function reverse(lng,lat){const url='https://nominatim.openstreetmap.org/reverse?format=jsonv2&zoom=18&addressdetails=1&accept-language=pt-BR&lat='+encodeURIComponent(lat)+'&lon='+encodeURIComponent(lng);const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('reverse');return r.json()}
  async function validateAndSetPoint(lng,lat,fly=true,fromDrag=false){if(state.checking)return false;if(!withinBounds(lng,lat)){setStatus('Esse ponto está fora da área do Limpaê. Escolha Salvador ou Lauro de Freitas.','error');if(fromDrag&&state.coords&&state.marker)state.marker.setLngLat([state.coords.lng,state.coords.lat]);return false}state.checking=true;setStatus('Confirmando o município…');try{const data=await reverse(lng,lat);if(!localResult(data.display_name)){if(fromDrag&&state.coords&&state.marker)state.marker.setLngLat([state.coords.lng,state.coords.lat]);setStatus('O ponto não pertence a Salvador nem a Lauro de Freitas.','error');return false}state.address=displayAddress(data.display_name);placeMarker(lng,lat,fly);geoInput.value=state.address;setStatus('Local confirmado.','success');return true}catch(e){if(fromDrag&&state.coords&&state.marker)state.marker.setLngLat([state.coords.lng,state.coords.lat]);setStatus('Não consegui confirmar o município agora. Tente novamente ou use a busca por endereço.','error');return false}finally{state.checking=false;updateSelected()}}

  function initMap(){if(!window.maplibregl){setStatus('O mapa não carregou. Verifique sua conexão e atualize a página.','error');return}state.map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:CENTER,zoom:11.2,minZoom:10,maxZoom:19,maxBounds:BOUNDS,attributionControl:true});state.map.addControl(new maplibregl.NavigationControl({showCompass:false}),'bottom-right');state.map.on('click',e=>validateAndSetPoint(e.lngLat.lng,e.lngLat.lat,true));state.map.on('error',()=>{if(!state.map.loaded())setStatus('O mapa está demorando para carregar. Confira a internet e tente novamente.','error')})}

  async function searchLocal(){const q=geoInput.value.trim();resultsEl.innerHTML='';resultsEl.classList.remove('show');if(q.length<3){setStatus('Digite pelo menos 3 letras de uma rua, bairro ou ponto.','error');return}setStatus('Buscando somente em Salvador e Lauro de Freitas…');document.getElementById('geoSearch').disabled=true;try{const params=new URLSearchParams({format:'jsonv2',q:q+', Bahia, Brasil',limit:'7',countrycodes:'br',bounded:'1',viewbox:'-38.72,-12.72,-38.20,-13.15','accept-language':'pt-BR',addressdetails:'1'});const r=await fetch('https://nominatim.openstreetmap.org/search?'+params.toString(),{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('search');const raw=await r.json();const items=raw.filter(x=>localResult(x.display_name)).slice(0,5);if(!items.length){setStatus('Não encontrei esse local em Salvador ou Lauro de Freitas. Tente rua + bairro.','error');return}setStatus(items.length+' resultado(s) local(is).','success');resultsEl.classList.add('show');items.forEach(item=>{const b=document.createElement('button');b.type='button';b.className='search-result';const nice=displayAddress(item.display_name);const parts=nice.split(',');b.innerHTML='<strong>'+escapeHtml(parts.slice(0,2).join(', '))+'</strong><span>'+escapeHtml(parts.slice(2).join(', ').trim())+'</span>';b.addEventListener('click',()=>{state.address=nice;placeMarker(Number(item.lon),Number(item.lat),true);geoInput.value=nice;resultsEl.classList.remove('show');setStatus('Local confirmado.','success')});resultsEl.appendChild(b)})}catch(e){setStatus('A busca não respondeu agora. Você ainda pode tocar no mapa ou usar sua localização.','error')}finally{document.getElementById('geoSearch').disabled=false}}

  function useLocation(){const btn=document.getElementById('useLocation');if(!window.isSecureContext){setStatus('A localização do navegador precisa do site publicado em HTTPS. Use a busca ou o mapa neste teste local.','error');return}if(!navigator.geolocation){setStatus('Este navegador não oferece localização. Use a busca ou toque no mapa.','error');return}btn.disabled=true;setStatus('Pedindo sua localização…');navigator.geolocation.getCurrentPosition(async pos=>{btn.disabled=false;const {longitude,latitude,accuracy}=pos.coords;if(!withinBounds(longitude,latitude)){setStatus('Sua localização atual está fora de Salvador e Lauro de Freitas. Você pode buscar um endereço dentro da área.','error');return}const ok=await validateAndSetPoint(longitude,latitude,true);if(ok&&accuracy>150)setStatus('Local encontrado, mas o GPS está pouco preciso. Ajuste o pino no mapa se necessário.','success')},err=>{btn.disabled=false;const msg=err.code===1?'A permissão de localização foi negada. Libere o acesso no navegador ou use a busca.':err.code===3?'A localização demorou demais. Tente novamente ou use a busca.':'Não foi possível obter sua localização. Use a busca ou toque no mapa.';setStatus(msg,'error')},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}

  function locationValid(){if(!state.coords){setStatus('Defina o local antes de continuar.','error');return false}return true}
  function category(){return form.querySelector('input[name="category"]:checked')?.value||''}
  function detailsValid(){if(!category()){alert('Escolha o tipo de resíduo encontrado.');return false}return true}
  function risks(){return [...form.querySelectorAll('input[name="risk"]:checked')].map(i=>i.value)}
  function renderReview(){const cat=category();const r=risks();const desc=document.getElementById('description').value.trim();const anon=anonymous.checked;const name=document.getElementById('reporterName').value.trim();const contact=document.getElementById('contact').value.trim();const photoHtml=state.photos.length?'<div class="review-photo-strip">'+state.photos.map(p=>'<img src="'+p+'" alt="Foto anexada">').join('')+'</div>': 'Nenhuma foto anexada';document.getElementById('review').innerHTML='<div class="review-row"><span class="key">Local</span><span class="value">'+escapeHtml(state.address||'Ponto marcado no mapa')+'</span></div><div class="review-row"><span class="key">Categoria</span><span class="value">'+escapeHtml(categoryLabels[cat]||'—')+'</span></div><div class="review-row"><span class="key">Fotos</span><span class="value">'+photoHtml+'</span></div><div class="review-row"><span class="key">Riscos</span><span class="value">'+(r.length?r.map(x=>escapeHtml(riskLabels[x])).join('<br>'):'Nenhum informado')+'</span></div>'+(desc?'<div class="review-row"><span class="key">Observação</span><span class="value">'+escapeHtml(desc)+'</span></div>':'')+'<div class="review-row"><span class="key">Identificação</span><span class="value">'+(anon?'Anônima':escapeHtml(name||'Sem nome')+(contact?'<br>'+escapeHtml(contact):''))+'</span></div>'}

  function compress(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=e=>{const img=new Image();img.onload=()=>{const scale=Math.min(1,1100/img.width);const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.72))};img.onerror=reject;img.src=e.target.result};fr.onerror=reject;fr.readAsDataURL(file)})}
  async function addPhotos(files){const remaining=4-state.photos.length;for(const f of [...files].slice(0,remaining)){if(!f.type.startsWith('image/'))continue;if(f.size>10*1024*1024){alert(f.name+' ultrapassa 10 MB.');continue}try{state.photos.push(await compress(f))}catch(e){}}renderPhotos()}
  function renderPhotos(){photosEl.innerHTML='';state.photos.forEach((src,i)=>{const d=document.createElement('div');d.className='photo';d.innerHTML='<img alt="Foto anexada"><button type="button" aria-label="Remover foto">×</button>';d.querySelector('img').src=src;d.querySelector('button').addEventListener('click',()=>{state.photos.splice(i,1);renderPhotos()});photosEl.appendChild(d)});photoCount.textContent=state.photos.length+' de 4 fotos'}
  function resetForm(){form.reset();anonymous.checked=true;contactFields.classList.add('hidden');state.photos=[];renderPhotos();clearPoint();showStep(1)}
  function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}

  document.getElementById('geoSearch').addEventListener('click',searchLocal);geoInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchLocal()}});document.getElementById('useLocation').addEventListener('click',useLocation);document.getElementById('resetMap').addEventListener('click',clearPoint);document.getElementById('next1').addEventListener('click',()=>{if(locationValid())showStep(2)});document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>showStep(Number(b.dataset.next))));document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>showStep(Number(b.dataset.back))));document.getElementById('next3').addEventListener('click',()=>{if(detailsValid())showStep(4)});
  anonymous.addEventListener('change',()=>contactFields.classList.toggle('hidden',anonymous.checked));document.getElementById('dropzone').addEventListener('click',()=>photosInput.click());document.getElementById('dropzone').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();photosInput.click()}});photosInput.addEventListener('change',()=>{addPhotos(photosInput.files);photosInput.value='' });
  form.addEventListener('submit',e=>{e.preventDefault();if(!locationValid()){showStep(1);return}if(!detailsValid()){showStep(3);return}document.getElementById('protocol').textContent='DEMO-'+String(Date.now()).slice(-6);modal.classList.add('show');document.body.style.overflow='hidden'});
  document.getElementById('closeModal').addEventListener('click',()=>{modal.classList.remove('show');document.body.style.overflow='';resetForm()});modal.addEventListener('click',e=>{if(e.target===modal)document.getElementById('closeModal').click()});
  initMap();updateSelected();renderPhotos();
})();
